name: document_management
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dio: ^5.3.0
  auto_size_text: ^3.0.0
  intl: ^0.18.0
  adaptive_dialog: ^1.9.0
  cached_network_image: ^3.2.1
  flutter_slidable: ^3.0.0
  focused_menu: ^1.0.5
  sliding_up_panel: ^2.0.0+1
  file_icon: ^1.0.0
  calendar_date_picker2: ^0.5.2
  mime: ^1.0.1
  open_filex: ^4.1.1
  file_picker: ^5.3.3
  photo_view: ^0.14.0
  image_picker: ^1.0.1
  flutter_file_dialog: ^3.0.1
  audioplayers: ^5.0.0
  webview_flutter: ^4.0.7
  permission:
    git:
      url: https://github.com/leovu/permission.git
      ref: 1.1.2
  gallery_saver: ^2.3.2
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.document_management
        pluginClass: DocumentManagementPlugin
      ios:
        pluginClass: DocumentManagementPlugin

  # To add assets to your plugin package, add an assets section, like this:

  assets:
    - assets/document_en.json
    - assets/document_vi.json
    - assets/ico/
